<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.ethz.abmt</groupId>
    <artifactId>abmt2026</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>abmt2026</name>

 <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <matsim.version>2026.0-2025w38</matsim.version>
    </properties>

     <repositories>
        <repository>
            <id>matsim</id>
            <name>MATSim Maven repository</name>
            <url>https://repo.matsim.org/repository/matsim/</url>
        </repository>
        
        <repository>
            <id>eqasim</id>
            <url>https://packagecloud.io/eth-ivt/eqasim/maven2</url>
        </repository>

        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.matsim</groupId>
            <artifactId>matsim</artifactId>
            <version>${matsim.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eqasim</groupId>
            <artifactId>core</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.2.4</version>
            <executions>
            <execution>
                <phase>package</phase>
                <goals>
                <goal>shade</goal>
                </goals>
                <configuration>
                <transformers>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                    <manifestEntries>
                        <Implementation-Vendor>Eqasim</Implementation-Vendor>
                        <Implementation-Version>${parent.groupId}</Implementation-Version>
                    </manifestEntries>
                    </transformer>
                </transformers>
                <filters>
                    <filter>
                    <artifact>*:*</artifact>
                    <excludes>
                        <exclude>META-INF/*.SF</exclude>
                        <exclude>META-INF/*.DSA</exclude>
                        <exclude>META-INF/*.RSA</exclude>
                    </excludes>
                    </filter>
                </filters>
                </configuration>
            </execution>
            </executions>
        </plugin>
        </plugins>
    </build>
</project>